apiVersion: apps/v1
kind: Deployment
metadata:
  name: will-deployment
  labels:
    app: will
spec:
  replicas: 3
  selector:
    matchLabels:
      app: will
  template:
    metadata:
      labels:
        app: will
    spec:
      containers:
      - name: will
        image: wil42/playground:v1
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: will-service
spec:
  selector:
    app: will
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080

